Iter5
kyrare/ya-metrics pull request #5
Opened 2024-04-07 13:26 UTC by kyrare

2024-04-09 23:10 UTC, avhitrov requested changes
Неверная реализация агента - не выделены счетчики и PollCount передается, как gauge. Гонки в данных на сервере. Также мелкие замечания в комментариях к коду.

2024-04-09 23:10 UTC, avhitrov commented on internal/service/agent/agent.go
> +		err := a.Client.Send(metrics.TypeGauge, metric, value)
Счетчик должен передаваться, имея тип counter, а не gauge. Счетчик должен соответствовать типу int, int64 или их производных. И, сразу забегая вперед, счетчик должен сбрасываться после каждой успешной отправки всех метрик. Иначе на сервере он будет увеличиваться в геометрической прогрессии.

2024-04-09 23:10 UTC, avhitrov commented on internal/application/handlers/home.go
> +		panic(err)
Не надо паник. Просто залогировать ошибку.

2024-04-09 23:10 UTC, avhitrov commented on internal/application/handlers/home.go
> +	w.Header().Add("Content-Type", "text/html; charset=utf-8")
Хорошим тоном является выставление явно статуса ответа.

2024-04-09 23:10 UTC, avhitrov commented on internal/application/handlers/update.go
> +
Хорошим тоном является выставление явно статуса ответа.

2024-04-09 23:10 UTC, avhitrov commented on internal/infrastructure/agent/in_memory.go
> +	values map[string]float64
Неплохо было бы разделить здесь gauges и counters

2024-04-09 23:10 UTC, avhitrov commented on internal/infrastructure/metrics/in_memory.go
> +	Counters map[string]float64
Мапы - структуры потоконебезопасные и в конкурентной среде (а http-сервер априори является конкурентным приложением, так как на каждый запрос пользователя хендлер открывается в отдельной горутине) должны защищаться блокировкой. Можно использовать либо sync.Mutex (sync.RWMutex), либо потокобезопасную мапу sync.Map.

https://t.me/bushigo/24

В данном случае получаем:
```
==================
WARNING: DATA RACE
Write at 0x00c000088ab0 by goroutine 741:
  runtime.mapassign_faststr()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map_faststr.go:203 +0x0
  github.com/kyrare/ya-metrics/internal/infrastructure/metrics.(*MemStorage).UpdateGauge()
      D:/work/src/github.com/kyrare/ya-metrics/internal/infrastructure/metrics/in_memory.go:21 +0x56
  github.com/kyrare/ya-metrics/internal/application/handlers.(*Handler).Update()
      D:/work/src/github.com/kyrare/ya-metrics/internal/application/handlers/update.go:29 +0x2f5
  github.com/kyrare/ya-metrics/internal/application/handlers.(*Handler).Update-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Previous read at 0x00c000088ab0 by goroutine 752:
  runtime.mapiternext()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map.go:867 +0x0
  github.com/kyrare/ya-metrics/internal/application/handlers.(*Handler).Home()
      D:/work/src/github.com/kyrare/ya-metrics/internal/application/handlers/home.go:16 +0x3bd
  github.com/kyrare/ya-metrics/internal/application/handlers.(*Handler).Home-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Goroutine 741 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x86c
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2985 +0xbc
  net/http.ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3239 +0x154
  github.com/kyrare/ya-metrics/internal/service/server.(*Server).Run()
      D:/work/src/github.com/kyrare/ya-metrics/internal/service/server/server.go:15 +0x2a
  main.main()
      D:/work/src/github.com/kyrare/ya-metrics/cmd/server/main.go:16 +0x69

Goroutine 752 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x86c
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2985 +0xbc
  net/http.ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3239 +0x154
  github.com/kyrare/ya-metrics/internal/service/server.(*Server).Run()
      D:/work/src/github.com/kyrare/ya-metrics/internal/service/server/server.go:15 +0x2a
  main.main()
      D:/work/src/github.com/kyrare/ya-metrics/cmd/server/main.go:16 +0x69
==================
```

2024-04-09 23:10 UTC, avhitrov commented on internal/application/handlers/get.go
> +		panic(err)
Аналогично - не надо паники.

2024-04-10 14:30 UTC, kyrare commented on internal/infrastructure/agent/in_memory.go
> +	values map[string]float64
не понимаю зачем? это хранилище для агента, на нем нет разделения gauges и counters

2024-04-10 15:42 UTC, kyrare commented on internal/application/handlers/update.go
> +
Сначала добавил w.WriteHeader, но начались предупреждения сыпаться что статус уже указан. Т.к. http.Error уже есть вызов w.WriteHeader

2024-04-14 22:11 UTC, avhitrov requested changes
Все критические замечания исправлены, все дискуссионные моменты не являются блокерами. То есть, работа хорошая, но заапрувить мне ее не дает одна опечатка в инициализации конфига (отметил в комментарии). Как только будет исправлена - будет апрув.

2024-04-14 22:11 UTC, avhitrov commented on internal/service/agent/config.go
> +		PollInterval:   time.Duration(reportInterval),
Вот здесь кое-что перепутано, из-за чего у меня чуть мигрень не случилась в процессе проверки. Потому как по коду все должно работать правильно, а по факту счетчик изменяется при каждой отправке только на единицу.

2024-04-15 22:37 UTC, avhitrov approved these changes
Все хорошо.

2024-04-16 19:55 UTC, merged