Iter9
kyrare/ya-metrics pull request #8
Opened 2024-04-30 08:18 UTC by kyrare

2024-04-30 15:58 UTC, Perederey requested changes
В целом все отлично, есть рекомендации, которые нужно сделать

2024-04-30 15:58 UTC, Perederey commented on cmd/agent/main.go
>  	agentStorage "github.com/kyrare/ya-metrics/internal/infrastructure/agent"
Надо сделать сортировку через go imports

2024-04-30 15:58 UTC, Perederey commented on cmd/agent/main.go
> +	logger, err := zap.NewDevelopment()
А если нужны разные zap? Если например у тебя прод?

2024-04-30 15:58 UTC, Perederey commented on internal/application/client/client.go
> +
Sprintf тут лишний, достаточно просто +

2024-04-30 15:58 UTC, Perederey commented on internal/application/client/client.go
> +	bytes, err := io.ReadAll(body)
Забыл закрыть body

2024-04-30 15:58 UTC, Perederey commented on internal/application/handlers/update_json.go
> +		http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
Тут бы сделать бы цепочку validators

2024-04-30 15:58 UTC, Perederey commented on internal/domain/metrics/type.go
> +	} else {
Лучше switch и default выходить с ошибкой

2024-04-30 15:58 UTC, Perederey commented on internal/infrastructure/metrics/in_memory.go
> +	file, err := os.Open(s.filePath)
Каждый раз открываешь файл? Надо один раз при запуске открывать и закрывать

2024-04-30 15:58 UTC, Perederey commented on internal/service/server/server.go
> +			time.Sleep(s.Config.StoreInterval * time.Second)
Надо переделать на ticker

2024-05-01 22:15 UTC, kyrare commented on internal/application/handlers/update_json.go
> +		http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)
Можно пример? не совсем понимаю что за validators и как их использовать

2024-05-02 15:47 UTC, Perederey approved these changes
Теперь отлично  👌

2024-05-07 17:37 UTC, merged